
name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - run: echo "Setting up JDK"

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - run: echo "Build status report=${{ job.status }}."

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: PokeFit.apk
          path: app/build/outputs/apk/debug/app-debug.apk